# Base Image: Python Slim (Lightweight)
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    ffmpeg \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip 
RUN pip install --no-cache-dir -r requirements.txt

# Additional manual installations for Wav2Lip and any extra requirements
RUN git clone https://github.com/zabique/Wav2Lip.git /app/Wav2Lip && \
    wget 'https://iiitaphyd-my.sharepoint.com/personal/radrabha_m_research_iiit_ac_in/_layouts/15/download.aspx?share=EdjI7bZlgApMqsVoEUUXpLsBxqXbn5z8VTmoxp55YNDcIA' -O '/app/Wav2Lip/checkpoints/wav2lip_gan.pth' && \
    wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "/app/Wav2Lip/face_detection/detection/sfd/s3fd.pth" && \
    pip install --no-cache-dir -r /app/Wav2Lip/requirements.txt


# Expose the application port
EXPOSE 8000

# Command to run the FastAPI server
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]